apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: featherlightdesign-net-tls
spec:
  secretName: featherlightdesign-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: featherlightdesign.net
  dnsNames:
    - featherlightdesign.net
    - www.featherlightdesign.net